### ISSUE TITLE
Clicking `+1 day` or `+1 week` buttons sends a message even if the body is empty 

### ISSUE THREAD

**Issue by ralphie02** [rymndhng/30clj#1]
![screen shot 2015-09-03 at 2 42 51 pm](https://cloud.githubusercontent.com/assets/3424736/9671768/2abc214c-524a-11e5-9b87-4eaf03804a0e.png)

**Comment by rymndhng** [comment]
![screen shot 2015-09-07 at 5 23 29 pm](https://cloud.githubusercontent.com/assets/1694040/9724029/3d681344-5585-11e5-87f6-7bd4a7dc6e7a.png)

Added some validation logic. Might not work perfectly.. but close enough. The datepicker's pretty messed up TBH and I'm not inclined to fix it since that's really browser dependent.
